---
title: "EC-RNASEq"
author: "Jongmin Kim"
format: html
editor: visual
---

## Before begin

-   'Session' -\> 'Set Working Directory' -\> choose where all the files are

-   If below packages are not installed yet, 'Tools' -\> 'Install Packages...'

load packages and read in data tables

```{r}
# Load required plotting and data manipulation libraries
library (edgeR)
library (limma)
library (RColorBrewer)
library (mixOmics)
library (HTSFilter)

# Import data (below example)
# GeneID	ST5	ST6	ST7	STx
# Wdr13		370	431	453	504
# Npnt		599	582	655	731
# Twnk		901	969	1000	1165
# Gene X	.	.	.	.

rawCountTable <- read.table ("S0-5678-exp-ID.txt", header=TRUE, sep="\t", row.names = 1)


# (Optional) If you want to subset your samples 
# rawCountTable1234 <- rawCountTable[-c(1,2,3,4)]


# Import study design (below example)
# File  condition
# ST5   Mut
# ST6   WT
# ST7   Mut
# STx   .

sampleInfo <- read.table("design2.csv", header = TRUE, sep=",", row.names = 1)

```

Reshapes the data from a wide format (one column per sample) to a long format so that each sample’s expression values can be easily plotted with ggplot.

```{r}
#| echo: true
EC_long <- EC %>%
  pivot_longer(
    cols = -ID,               # all columns except ID
    names_to = "Sample",      # new column with sample names
    values_to = "Expression"  # new column with numeric values
  )
```

Draw a box plot

```{r}
#| echo: true
# Create a boxplot of expression values across samples
ggplot(EC_long, aes(x = fct_inorder(Sample), y = Expression)) +

  # Draw boxplots and make outliers semi-transparent
  geom_boxplot(outlier.alpha = 0.1) +

  # Set y-axis range without removing data outside the limits (safe zoom)
  coord_cartesian(ylim = c(-1, 11)) +

  # Use a clean black-and-white theme
  theme_bw() +

  # Rotate x-axis labels for readability
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +

  # Axis labels
  labs(x = "Sample", y = "Expression")
```

Draw a scatter plot

```{r}
#| echo: true
#| label: cbx7-scatter
#| fig-cap: "Scatter plot of CBX7i_000 vs CBX7i_125 with EC genes highlighted."

ggplot(all, aes(x = CBX7i_000, y = CBX7i_125)) +

  # Plot all genes as gray, semi-transparent points
  geom_point(size = 2, shape = 19, alpha = 0.1) +

  # Set x/y-axis ranges
  scale_x_continuous(limits = c(0, 16)) +
  scale_y_continuous(limits = c(0, 16)) +

  # Clean, minimal theme
  theme_classic() +

  # Add diagonal (y = x) reference line
  geom_abline(intercept = 0, slope = 1, color = "gray") +

  # Add EC genes: outer black circle (slightly larger)
  geom_point(
    data = ESC,
    aes(x = CBX7i_000, y = CBX7i_125),
    shape = 19,
    color = "black",
    size = 2.5,
    alpha = 1
  ) +

  # Add EC genes: inner red point (slightly smaller)
  geom_point(
    data = EC,
    aes(x = CBX7i_000, y = CBX7i_125),
    shape = 19,
    color = "red",
    size = 2,
    alpha = 1
  )

```
